default_node = "127.0.0.1:9000"

[fee_config]
fee_type = "Percent"
value = 0.1

[[contacts]]
name = "Alice"
key = "../miner/alice.pub.pem"


[[my_keys]]
public = "../miner/bob.pub.pem"
private = "../miner/bob.priv.cbor"
