default_node = "127.0.0.1:9001"

[fee_config]
fee_type = "Percent"
value = 0.1

[[contacts]]
name = "Alice"
key = "../validator/alice.pub.pem"


[[my_keys]]
public = "../validator/bob.pub.pem"
private = "../validator/bob.priv.cbor"
